---
- name: Disable access for root with password
  hosts: all
  become: true
  tasks:
    - name: disable root
      ansible.builtin.lineinfile:
        dest: /etc/ssh/sshd_config.d/01-permitrootlogin.conf
        regexp: '^PermitRootLogin'
        line: "PermitRootLogin no"
        state: present
        backup: yes
      notify:
        - restart ssh

  handlers:
  - name: restart ssh
    ansible.builtin.service:
      name: sshd
      state: restarted
